version: "3.8"

services:

  db:
    image: postgres
    container_name: cloud_db
    ports:
      - 5432:5432
    volumes:
      - ./storage_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: su
      POSTGRES_PASSWORD: 159753
      POSTGRES_DB: diploma_cloud

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: diploma_cloud
    ports:
      - 9999:9999
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/diploma_cloud

  front:
    build:
      context: frontend/netology-diplom-frontend
      dockerfile: Dockerfile
    container_name: cloud_frontend
    ports:
      - 8081:8080