CREATE TABLE max_cloud_com
(
    id         int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    path       VARCHAR      NOT NULL,
    filename   VARCHAR(100) NOT NULL,
    sizeKB     bigint       NOT NULL,
    loaddate   TIMESTAMP    NOT NULL,
    deleted    boolean      NOT NULL,
    deletedate TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE alex_cloud_com
(
    id         int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    path       VARCHAR      NOT NULL,
    filename   VARCHAR(100) NOT NULL,
    sizeKB       bigint       NOT NULL,
    loaddate   TIMESTAMP    NOT NULL,
    deleted    boolean      NOT NULL,
    deletedate TIMESTAMP,
    PRIMARY KEY (id)
);

CREATE TABLE admin_cloud_com
(
    id         int          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    path       VARCHAR      NOT NULL,
    filename   VARCHAR(100) NOT NULL,
    sizeKB       bigint       NOT NULL,
    loaddate   TIMESTAMP    NOT NULL,
    deleted    boolean      NOT NULL,
    deletedate TIMESTAMP,
    PRIMARY KEY (id)
);
